### ISSUE TITLE
Retagging existing manifest lists

### ISSUE THREAD

**Issue by d7415** [estesp/manifest-tool#105]
In https://github.com/estesp/manifest-tool/issues/31#issuecomment-308478777 and https://github.com/estesp/manifest-tool/pull/32#issuecomment-308506211 there was discussion of possible remote tagging capabilities in either `manifest-tool` or `docker manifest`, but I can't find any results.

My goal: Take an existing multi-arch tag (from `docker buildx`) and apply a new tag to it, without rebuilding the image. This is being done in CI, so the machine re-tagging must get any source data from Docker Hub.

Trying to use `manifest-tool` as-is results in `You specified a manifest list entry from a digest that points to a current manifest list. Manifest lists do not allow recursion` for me either using a YAML template or something like `manifest-tool push from-args --platforms linux/arm/v7,linux/arm/v6,linux/arm64,linux/amd64 --template repo/image:testing --target repo/image:latest`.

Reading the docs for `docker manifest` doesn't seem to have anything matching this use-case.

Can anyone point me in the right direction, or is this still "not yet"?

**Comment by jonjohnsonjr** [comment]
> Manifest lists do not allow recursion

Unrelated, but I don't think this is actually true either?

> My goal: Take an existing multi-arch tag (from docker buildx) and apply a new tag to it, without rebuilding the image. This is being done in CI, so the machine re-tagging must get any source data from Docker Hub.

FWIW, I maintain a tool that can do this via [`crane tag`](https://github.com/google/go-containerregistry/blob/master/cmd/crane/README.md). I believe [`skopeo copy`](https://github.com/containers/skopeo/blob/master/docs/skopeo-copy.1.md) will also do this.

**Comment by estesp** [comment]
All the code bits are here in `manifest-tool` to do a "remote tag" but given the only commands exposed are `push` and `inspect`, it would require adding a new `tag` command, and I feel like other tools, like @jonjohnsonjr mentioned, exist to provide that feature without me starting to expand `manifest-tool` into a general registry client.

**Comment by d7415** [comment]
Hi. Sorry - I was going to return here when I'd tried those out, but haven't had time. I'm happy to close this in light of those options. Thanks @jonjohnsonjr!
