### ISSUE TITLE
Add usage example

### ISSUE THREAD

**Issue by amouat** [estesp/manifest-tool#15]
There is sort of half an example, but it doesn't work as it's missing the pushml command.  

You could also paste the output of `manifest --help`.

Merry Xmas :christmas_tree: :)

**Comment by estesp** [comment]
Thanks @amouat ; sorry just getting back to this now.  Just merged #16 from @luxas and he or I will need to get the README up to date with the new command structure! It's on my TODO list now.

**Comment by estesp** [comment]
I've updated the `README.md` with a proper example for the YAML form for `push`; @luxas would you mind submitting a good example for the command line version?

**Comment by hrw** [comment]
What about "inspect" example?

**Comment by estesp** [comment]
Added `inspect` example and better/clearer documentation for all commands in #37
