### ISSUE TITLE
Please provide release binaries for linux-arm64

### ISSUE THREAD

**Issue by DieterReuter** [estesp/manifest-tool#17]
@estesp It would be great if we'd have binaries for linux/arm64 created at release time, I guess you just have to include this new arch into your cross-compile build script. :smirk: 

There are some cool aarch64 servers out there which didn't have the possibility to run arm 32bit code, I'm thinking about the  Cavium ThunderX powered packet.net 2A servers I'm working with.

**Comment by estesp** [comment]
@DieterReuter happy to do so..totally forgot to do arm64; will add it to the release. Thanks!

**Comment by DieterReuter** [comment]
Cool.

**Comment by estesp** [comment]
I just released v0.4.0 and included arm64 binaries in the release: https://github.com/estesp/manifest-tool/releases/tag/v0.4.0

Let me know if you get a chance to test on your board. Thanks!

**Comment by DieterReuter** [comment]
Great, thanks!
