### ISSUE TITLE
unsupported os/arch or os/arch/variant combination: linux/amd64/v8

### ISSUE THREAD

**Issue by hgraca** [estesp/manifest-tool#185]
Hi, 

I'm having this issue coming up:

`Manifest entry for image ...:5001/.../my-image:my-tag-arm64-8f483868 has unsupported os/arch or os/arch/variant combination: linux/amd64/v8`

However, this only happens when I use the latest version of manifest-tool, if I use version 1.0.3 it works fine.

I created the images with the commands:

`docker build --pull  --platform linux/arm64 -t "...:5001/.../my-image:my-tag-arm64-8f483868" -f "images/my-image/Dockerfile" .`
`docker build --pull  --platform linux/amd64 -t "...:5001/.../my-image:my-tag-arm64-8f483868" -f "images/my-image/Dockerfile" .`

**Comment by tianon** [comment]
This sounds like it's a typo - you've got `amd64` where I think you meant `arm64` :grimacing:

**Comment by tianon** [comment]
(the "levenshtein distance" between those is a literal crime :weary: :see_no_evil:)

**Comment by estesp** [comment]
I think @tianon's response is correct; your pasted command shows an incorrect arch: amd64 vs. arm64. I assume if you fix that typo you should no longer get the error. Please re-open if we misunderstood your issue. If it works with v1.0.3 that's a bug and maybe the v1 codebase didn't have precise checking for os/arch/variant combinations?

**Comment by hgraca** [comment]
Tkx for your replies, and apologies for being slow, only saw this now.

In any case, I went another way, so I guess I must have made a typo.

Again, tkx for the support.

**Comment by chimisu** [comment]
hey guys,I got the same issue as below:
`/kaniko/executor --context ${params.workspace} --custom-platform linux/amd64 --dockerfile ${params.workspace}/Dockerfile --destination ${params.imageTag}-amd64
        /kaniko/executor --context ${params.workspace} --custom-platform linux/arm64 --dockerfile ${params.workspace}/Dockerfile --destination ${params.imageTag}-arm64

manifest-tool --username xxxx --password xxxx push from-args --platforms linux/amd64,linux/arm64 --template ${params.imageTag}-ARCH --target ${params.imageTag}
`

time="2024-01-25T02:27:08Z" level=fatal msg="unable to create platform object for manifest sha256:9f8b1bc79a1d286642053c9b0c766864a5055b8d83881d0b4a1b5dd8d66164f2: manifest entry for image harbor.roche-digital.cn/digital-platform/cdp-edge-application-service:feature_with_image_arm_test_c3491cc_83_202401251010-amd64 has unsupported os/arch or os/arch/variant combination: linux/amd64/v8"

I cant find the problem.
