### ISSUE TITLE
New release for Golang CVE

### ISSUE THREAD

**Issue by jingyuanliang** [estesp/manifest-tool#205]
Will we get a new release for the recent Golang stdlib CVEs?

**Comment by estesp** [comment]
I had some issues in `main` since the last release that needed solving; now that I believe those are resolved, and I've done the stdlib and Go version updates, I should be able to release 2.0.7 in the next few days.

**Comment by jwboyer** [comment]
There's also now a containerd CVE which is conveniently fixed by some updated vendoring in the latest commits.  Is that new release coming soon?

**Comment by estesp** [comment]
Yes; I waited because I wanted to verify there was no new issue with credential helpers that came up in another report; I was able to verify credential helpers are working properly yesterday, so now I can cut a release. Probably will get it out before the end of the day since there is nothing else other than starting the process left

**Comment by jwboyer** [comment]
Nice!  You remain one of my heroes :smile:

**Comment by estesp** [comment]
Release v2.0.7 is in process in GitHub Actions: https://github.com/estesp/manifest-tool/actions/runs/4327070051

**Comment by estesp** [comment]
Ugh; there is an issue with public repo inspect related to the 401 challenge returned by DockerHub even for public images. Please don't update to v2.0.7 for now; I will have a fix soon

**Comment by estesp** [comment]
Release v2.0.8 is in process; sorry for the churn!

**Comment by estesp** [comment]
v2.0.8 is now final and working; container images are being pushed to DockerHub

**Comment by estesp** [comment]
> Nice! You remain one of my heroes 😄

By the way, you are too kind! Hope you are doing well @jwboyer!
