### ISSUE TITLE
[feature request] allow to display OCI image manifest

### ISSUE THREAD

**Issue by marcosnils** [estesp/manifest-tool#222]
Sometimes I want to check what an image manifest looks like to see its OCI configuration (entrypoint, cmd, env vars, etc) without having to pull the actual image. I'd be awesome if `manifest-tool` could  with that so I don't have to `pull` the image and perform an `inspect` afterwards :pray:

**Comment by estesp** [comment]
PR #225 expands config objects in raw JSON (when used with `--raw`) when the result is a single image (not index/manifest lists). If you want to expand the config of an image in an index/manifest list, you can grab the sha256 from the index output and pass it back to inspect with `--expand-config` to get the config for that single image entry.  This seems like a reasonable compromise to having to complicate the index/manifest list output with different JSON structs depending on whether we are expanding the config section or not.
