### ISSUE TITLE
github.com/docker/docker/cli/config no longer exists, but is used by v2/cmd/manifest-tool/main.go

### ISSUE THREAD

**Issue by thockin** [estesp/manifest-tool#240]
So much for stable APIs :(

https://github.com/moby/moby/commit/ef7ab7bde855c10e3393f23ad7df3a869e5a409a#diff-5225a3b1610745a9172e4bd17ea7779d3845ed4b7672b0917b1faf7964ac4730

**Comment by estesp** [comment]
#244 should solve this

**Comment by estesp** [comment]
The latest release (v2.1.4) has been tagged/pushed with the fix from #244, so you should be able to try a dependent "go get" with the latest Docker and not get the compilation failure!
