### ISSUE TITLE
[feature] package build for Alpine

### ISSUE THREAD

**Issue by iamasmith** [estesp/manifest-tool#253]
Since the golang images that many use are based on Alpine it would be really good to be able to add manifest-tool to a build image with an apk add either in a build stage or baked into an image based on preference.

This is a really useful tool and I can see people might want to use it in various pipeline stages and it might help if it was available without an extra build step.

Happy to provide something that you can forward for an aports submission - I'm sure you are more than capable but who knows who has the time for these things.

Extra context: Some might find it difficult or encounter edge cases to add an extra step to use the vanilla container depending on the flexibility around adding auth helpers needed for cloud services etc. So doing this might help in that respect.

**Comment by estesp** [comment]
Thanks; I've added an aports merge request: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/62939

**Comment by iamasmith** [comment]
Thanks, I'll thumbs up on it when my activation email comes through.
For extra context, particularly on Gitlab, some runners need a shell and I didn't check if your image was built from scratch but for things like kaniko you end up using the debug version to get a shell for the runner to use.
Being able to apk add the package along with other common build tools really helps on pipelines.

**Comment by iamasmith** [comment]
Looks like it has some linting issues.

**Comment by estesp** [comment]
It's now published in edge-testing: https://pkgs.alpinelinux.org/packages?name=manifest-tool&branch=edge&repo=&arch=&maintainer=

I think we can close this, but let me know if there is anything else necessary here

**Comment by iamasmith** [comment]
Excellent, many thanks Phil
