### ISSUE TITLE
Container image build/pish failure for v2.1.7

### ISSUE THREAD

**Issue by aarongoldenthal** [estesp/manifest-tool#260]
The Linux container build/push job, and therefore multi-platform build/push job, [failed for v2.1.7](https://github.com/estesp/manifest-tool/actions/runs/9767589865) so they're not all available on [Docker hub](https://hub.docker.com/r/mplatform/manifest-tool) (for example, the only Alpine images are `alpine_linux_arm_v7_v2.1.7` and `alpine_linux_arm_v6_v2.1.7`).

**Comment by estesp** [comment]
Thanks @aarongoldenthal ; was debugging a bit yesterday and I need to respin the release after I figure out why the credential helpers didn't end up in the directory they used to during build; I will fix and generate a new build when I get a chance

**Comment by estesp** [comment]
Looks like it was a temporary failure; possibly because I ran it so close to the 1.22.5 images being deployed on DockerHub? Regardless, all images are properly published now! Thanks
