### ISSUE TITLE
New release to capture new platforms

### ISSUE THREAD

**Issue by geraldwuhoo** [estesp/manifest-tool#277]
Any chance at a new release to add support for the new platforms added in https://github.com/estesp/manifest-tool/commit/f2bae608b76e7d18b23394fb68be835188c16601? I'm particularly interested in `wasip1` OS target.

I'm sure others are also eagerly waiting since this seems to be the first platform list regeneration in years.

Thanks!

**Comment by estesp** [comment]
Release `v2.1.9` was just cut! Final images are still pushing via GitHub Actions, but the release is created: https://github.com/estesp/manifest-tool/releases/tag/v2.1.9
