### ISSUE TITLE
Does not work for Azure Container Registry (ACR)

### ISSUE THREAD

**Issue by AceHack** [estesp/manifest-tool#55]
I am able to pull and push using docker without any issues and I just used the standard docker login command.

Pushing MultiArch File /opt/vsts/work/_temp/748ea4a0-2253-467f-86c9-d117f52032e7/multiarch.yml using /opt/vsts/work/_tasks/PushDockerMultiArchTag_013ac686-e3c8-4414-aebd-15ec11e897ed/0.2.20/tools/manifest-tool-linux-amd64
time="2018-01-30T21:19:30Z" level=debug msg="endpoints: [{false https://itronarchcr.azurecr.io v2 false true 0xc420001c80} {false http://itronarchcr.azurecr.io v2 false true 0xc420001c80} {false https://itronarchcr.azurecr.io v1 false true 0xc420320600} {false http://itronarchcr.azurecr.io v1 false true 0xc420320600}]" 
time="2018-01-30T21:19:30Z" level=debug msg="repoName: dotnet-build" 
time="2018-01-30T21:19:30Z" level=info msg="Retrieving digests of images..." 
time="2018-01-30T21:19:30Z" level=debug msg="authConfig for itronarchcr.azurecr.io: ********" 
time="2018-01-30T21:19:30Z" level=debug msg="endpoints: [{false https://itronarchcr.azurecr.io v2 false true 0xc420001e00} {false http://itronarchcr.azurecr.io v2 false true 0xc420001e00}]" 
time="2018-01-30T21:19:30Z" level=debug msg="Trying to fetch image manifest of itronarchcr.azurecr.io/dotnet-build repository from https://itronarchcr.azurecr.io v2" 
time="2018-01-30T21:19:31Z" level=debug msg="Increasing token expiration to: 60 seconds" 
time="2018-01-30T21:19:32Z" level=info msg="Image \"itronarchcr.azurecr.io/dotnet-build:2.0.5-ci.master-windows\" is digest sha256:29e0153aa5a02abd004553bdcefd267f9089d1f473ceca533f86820af9799c86; size: 3028" 
time="2018-01-30T21:19:32Z" level=debug msg="authConfig for itronarchcr.azurecr.io: ********" 
time="2018-01-30T21:19:32Z" level=debug msg="endpoints: [{false https://itronarchcr.azurecr.io v2 false true 0xc4202c4480} {false http://itronarchcr.azurecr.io v2 false true 0xc4202c4480}]" 
time="2018-01-30T21:19:32Z" level=debug msg="Trying to fetch image manifest of itronarchcr.azurecr.io/dotnet-build repository from https://itronarchcr.azurecr.io v2" 
time="2018-01-30T21:19:33Z" level=debug msg="Increasing token expiration to: 60 seconds" 
time="2018-01-30T21:19:34Z" level=info msg="Image \"itronarchcr.azurecr.io/dotnet-build:2.0.5-ci.master-linux\" is digest sha256:771a838bb6e73addf6bde9f505098911c83c2dbf3aee8d6d6eb6451d8b5beba1; size: 2014" 
time="2018-01-30T21:19:34Z" level=debug msg="Manifest list push url: https://itronarchcr.azurecr.io/v2/library/dotnet-build/manifests/2.0.5-ci.master" 
time="2018-01-30T21:19:34Z" level=debug msg="mediaType of manifestList: application/vnd.docker.distribution.manifest.list.v2+json" 
time="2018-01-30T21:19:34Z" level=debug msg="authConfig for itronarchcr.azurecr.io: ********" 
time="2018-01-30T21:19:34Z" level=debug msg="Increasing token expiration to: 60 seconds" 
time="2018-01-30T21:19:34Z" level=fatal msg="Registry push unsuccessful: response 401: 401 Unauthorized"

**Comment by rcastill** [comment]
I'm receiving 401 Unauthorized trying to push to Azure registries as well. Is this planned to be supported?

**Comment by AceHack** [comment]
@rcastill I ended up using docker CLI 18.02 RC with client-side experimental flag enabled.  I just included the executable for Windows and Linux in my custom VSTS task.  the docker manifest commands didn't need any access to the docker daemon so it worked just fine.  Thanks.

**Comment by rcastill** [comment]
@AceHack thanks! however I haven't been able to find how to enable experimental flag on client-side. All the documentation talks about daemon experimental features. Can you point me in the right direction?

**Comment by AceHack** [comment]
Add `"experimental": "enabled"` to the docker cli config file.  There is an environment variable you can use to point to the folder that the config file is in DOCKER_CONFIG.

The default is C:\Users\astainba\.docker\config.json on windows.

**Comment by estesp** [comment]
@rcastill please let me know if `docker manifest` with the same credentials works for you. It looks like in the debug log it found your credentials (it uses the same from `docker login`) and was using them, but I haven't had a chance to verify that Azure Container Registry supports manifest list media type (and maybe the `401 Unauthorized` is a red herring?) 

Wondering if @stefanscherer knows or has done anything with Azure registry?

If `docker manifest` works then I would like to dig a bit more and figure out if `manifest-tool` is doing something differently (the code is nearly the same).

**Comment by rcastill** [comment]
@AceHack I had tried that (instead I used "experimental": true), thanks!

@estesp I can confirm it works with `docker manifest`. I successfully deployed an image to a linux 64 machine and a raspberry pi with the same reference.

**Comment by AceHack** [comment]
@estesp Yes I can confirm too, that `docker manifest` works and Azure Container Registry works fine with manifest list media type.  The 401 only comes from using manifest-tool.  Thanks.

**Comment by estesp** [comment]
@AceHack could you share your input yaml file with me? I have an azurecr account now and want to make sure I test the same thing you test; I think I know the source of the issue, but need to confirm.

**Comment by estesp** [comment]
This is corrected by PR #56; sorry about that; some code that was in here for helping @tianon push to the library repos in DockerHub wasn't fully tested and had a bug!
