### ISSUE TITLE
Error from manifest-tool against GCR

### ISSUE THREAD

**Issue by thockin** [estesp/manifest-tool#61]
This seems new, so possibly something changed in GCR, but I am not sure where to look.  @mattmoor too ?

```
$ manifest-tool inspect staging-k8s.gcr.io/coredns:1.2.4__amd64_linux
FATA[0000] unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication 
```

vs

```
$ docker inspect staging-k8s.gcr.io/coredns:1.2.4__amd64_linux
[
    {
        "Id": "sha256:d35fe8670379d749764757bc2ea43f7f7dac013ee04a2440be8607dadc8e83dd",
        "RepoTags": [
            "staging-k8s.gcr.io/coredns:1.2.4__amd64_linux"
        ],
        "RepoDigests": [
...
```

Can you lend me a clue?

**Comment by thockin** [comment]
I reinstalled everything and re-enabled gcloud auth and re-enabled docker experimental and now it seems to work...

**Comment by thockin** [comment]
It's back.  I have no idea why.

```
$ manifest-tool inspect staging-k8s.gcr.io/coredns:1.2.5__amd64_linux
FATA[0000] unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication 
```

vs

```
$ docker inspect staging-k8s.gcr.io/coredns:1.2.5__amd64_linux
[
    {
        "Id": "sha256:bd254cf7211182cc29b420382b769c2a0228f5ef0bc27d5690db62afb2bf6ad3",
        "RepoTags": [
            "staging-k8s.gcr.io/coredns:1.2.5__amd64_linux"
        ],
        "RepoDigests": [
            "coredns/coredns@sha256:bbf4ed2d6b6b5bf0d0ffb81a9002f3b8bdf509ab13fb5647e36fefa2d565096e",
            "staging-k8s.gcr.io/coredns@sha256:bbf4ed2d6b6b5bf0d0ffb81a9002f3b8bdf509ab13fb5647e36fefa2d565096e"
        ],
...
```

It seems that the error is coming from deep within vendored docker code.  I can't explain this.  @estesp any clues?

**Comment by estesp** [comment]
@thockin Hmm..

Happy to try and investigate; is it actually an authenticated image repository? Do you normally require credentials to view or pull that image?

**Comment by thockin** [comment]
It's supposed to be a public repo with no read-auth required.  It has worked in the past - I really don't know what is happening or where to look.

**Comment by estesp** [comment]
With no gcloud auth setup in my Docker install I am unable to inspect that image. No object found. How do I find Jim Johnsons GitHub ID while on my phone? He can probably help figure out from the gcr.io side.

**Comment by thockin** [comment]
I am wrong, it's not public (should be, different issue).  It is auth'ed.

But I am authenticated.  I can `docker push` and `docker pull` to that repo, but manifest-tool can't read it. 

I've configured all my docker auth helpers, and so on.

**Comment by estesp** [comment]
@thockin I'm not sure how it ever works, but sadly I've never had time to add credential helper support to `manifest-tool`, so if your `~/.docker/config.json` points to credential helpers instead of having an actual token, `manifest-tool` can't use it and therefore doesn't auth.

You can use a cloud's client tools to get an actual token auth string and pass it to `--user` and `--password` in `manifest-tool`; I know I've tested that with gcloud in the past and it worked.

**Comment by thockin** [comment]
I'm not sure what magic incantation of gcloud gets me a credential that works in this context.  Awesome.  Thanks for the help, I'll keep digging.

**Comment by estesp** [comment]
`$ gcloud auth print-access-token`

You can then use the ID `oauth2accesstoken` as user id string and the token from above as password and use them as flags to the `manifest-tool` command line. This is mostly from [here](https://cloud.google.com/container-registry/docs/advanced-authentication#access_token)

**Comment by mattmoor** [comment]
yeah see: https://cloud.google.com/container-registry/docs/advanced-authentication#access_token
