### ISSUE TITLE
OS Variant info

### ISSUE THREAD

**Issue by DirtyCajunRice** [estesp/manifest-tool#68]
As arm has (for example) v6 and v7 variants, it would be awesome to allow for 'if OS/ARCH/VARIANT use variant" else OS/ARCH

**Comment by estesp** [comment]
Just to make sure I understand, is your `if`/`else` representing a decision flow on the runtime side when pulling a manifest list-based image on ARM? Or do you mean an improvement to how ARM images are built with tools like `manifest-tool`?

**Comment by DirtyCajunRice** [comment]
the former. im currently making my own yaml on the fly to feed to manifest-tool but only because it is variant unaware in the manifest. 
https://gist.github.com/DirtyCajunRice/f05d8f66c8d8a5ce90a26a760c1cccd9

**Comment by tianon** [comment]
Unfortunately, individual images don't include "variant" in their metadata (nor do they have a slot for it). :disappointed:

**Comment by DirtyCajunRice** [comment]
so the way im doing it is the only way? if so thats absolutely fine if so just want clarity

**Comment by tianon** [comment]
Definitely the only way I'm aware of, unfortunately.

**Comment by tianon** [comment]
(I say, as the author of https://github.com/estesp/manifest-tool/pull/21 which added the "autodetection" behavior in the first place. :sweat_smile:)

**Comment by DirtyCajunRice** [comment]
haha! i appreciate the prompt info. thanks for all it can do!
