### ISSUE TITLE
Build a multi-arch image of manifest-tool

### ISSUE THREAD

**Issue by ekristen** [estesp/manifest-tool#73]
I think you should build docker images for each architecture you build the tool for and publish to estesp/manifest-tool and use manifest-tool to publish the manifest on the tag at release time. 

You would be using your own tool and it would make the official image of your tool available for use in container based CI/CD systems like Drone, GitLab CI, etc ...

**Comment by estesp** [comment]
As soon as I build a tag (e.g. **v1.0.0-rc2**) of this repo, an image on DockerHub named `mplatform/manifest-tool` will appear which will support ppc64le,s390x,armv7,arm64,amd64 on Linux and amd64 on Windows.

**Comment by ekristen** [comment]
Sweet!

**Comment by estesp** [comment]
v1.0.0-rc2 is on DockerHub!
```
$ docker run --rm mplatform/mquery mplatform/manifest-tool:latest
Image: mplatform/manifest-tool:latest
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm
   - linux/arm64
   - linux/ppc64le
   - linux/s390x
   - windows/amd64:10.0.14393.2312
```

**Comment by ekristen** [comment]
Awesome!

**Comment by StefanScherer** [comment]
Thanks @estesp that is awesome!
