### ISSUE TITLE
schema version 1 manifest shows as having zero layers

### ISSUE THREAD

**Issue by tianon** [estesp/manifest-tool#74]
There was a blip of Docker Hub acting up recently while our arm64 server was pushing `golang` such that some of our tags managed to be pushed with a media type of `application/vnd.docker.distribution.manifest.v1+json`, which is all fine and well (`docker pull` can handle them just fine), but when inspecting them via `manifest-tool`, they show with `Layers: 0`:

```console
$ manifest-tool inspect golang@sha256:7cf1f7ccf392bd834eb91f02892f48992d3c2ba292c2198315a4637bb9454c30
golang@sha256:7cf1f7ccf392bd834eb91f02892f48992d3c2ba292c2198315a4637bb9454c30: manifest type: application/vnd.docker.distribution.manifest.v1+json
      Digest: sha256:7cf1f7ccf392bd834eb91f02892f48992d3c2ba292c2198315a4637bb9454c30
Architecture: arm64
          OS: linux
    # Layers: 0
```

I tried to dig into the code to find out why, and found that https://github.com/estesp/manifest-tool/blob/0da654f67ac65e08a9a5b961f20123eb0e3d15e4/docker/inspect_v1.go appears to know how to parse that format, but for some reason doesn't seem to be getting invoked here or something?  Sorry, not as familiar with the code/flow of this tool as I should be!

I also found the following which made me wonder if that `makeImageInspect` function perhaps needs to be updated to take v1 manifests into account?

https://github.com/estesp/manifest-tool/blob/0da654f67ac65e08a9a5b961f20123eb0e3d15e4/docker/inspect.go#L330-L337

For reference, here's the "repo-info" output for that same digest: https://github.com/docker-library/repo-info/blob/5dc0a8675b5ee26e8fc8d59dd9567fc7687a547c/repos/golang/remote/1.12-alpine.md#golang112-alpine---linux-arm64-variant-v8

The code that parses the manifests to generate that is at: https://github.com/docker-library/repo-info/blob/5dc0a8675b5ee26e8fc8d59dd9567fc7687a547c/.remote.pl#L228-L278

See also https://github.com/docker-library/golang/issues/269#issuecomment-473094518

**Comment by estesp** [comment]
Ok, I found the issue. Will get a PR submitted to solve it ASAP. The v1 fetch code actually works, so that's the good news :) Simply an error in creating the "inspect" object from the slightly different fields of the v1 manifest.

**Comment by estesp** [comment]
@tianon opened #75 to fix the image inspect of v1 manifests.
