### ISSUE TITLE
what does option os feature mean?

### ISSUE THREAD

**Issue by dongwangdw** [estesp/manifest-tool#79]
I am not sure if this tool can differentiate os distro, like ubuntu and redhat.
Then I got the os feature`--os-features stringSlice   Set operating system feature`, just ask this.

Is that possible to differentiate the two distro?

**Comment by dongwangdw** [comment]
what are supposed to be os features in linux? Is there any explanation on this option?

**Comment by estesp** [comment]
This is part of the OCI image specification, and defined here: https://github.com/opencontainers/image-spec/blob/master/specs-go/v1/descriptor.go#L57-L59

It is only used by Windows images today, and as the [official released spec](https://github.com/opencontainers/image-spec/releases/tag/v1.0.1) states for `os.features`:
```
When os is not windows, values are implementation-defined and
SHOULD be submitted to this specification for standardization.
```

**Comment by dongwangdw** [comment]
@estesp thanks for the reply. I try to differentiate linux distro with same arch(amd64) with this tool. I think it may not be possible.
