### ISSUE TITLE
[Bug] Need to supply username and password despite logging in

### ISSUE THREAD

**Issue by pugnascotia** [estesp/manifest-tool#92]
Git version: 856eb8cb437e226231713233bb10aa81ff9e10ac (i.e checked out master a couple days ago)
Go version: `go1.13.7 darwin/amd64`

I was experimenting with pushing manifests to private registry. I logged into it with `docker login`, push some images, but then when I tried to push the manifest, I got:

```
FATA[0001] Inspect of image "<image name>" failed with error: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

I repeated the push with `--username` and `--password` and it succeeded.

I have credentials in `$HOME/.docker/plaintext-passwords.json`, and my `$HOME/.docker/config.json` looks like this:

```json
{
  "auths": {
    "<private registry URL>": {},
    "https://index.docker.io/v1/": {}
  },
  "HttpHeaders": {
    "User-Agent": "Docker-Client/19.03.8 (darwin)"
  },
  "credsStore": "desktop",
  "experimental": "enabled",
  "stackOrchestrator": "swarm"
}
```

Let me know if I can give you any more information.

**Comment by estesp** [comment]
Unfortunately, this tool's auth support was built before credential helpers/cred stores were implemented  (or around the same time as that was being developed) so this code has no way to access credentials that are either stored in system credential stores or using new designs other than the simple site/user/[pass|token] format of the original docker auth config file.

This may be something that could be looked into for the future, but one of the downsides of being a totally separate tool not in the docker client and/or docker desktop universe.
